version: 2

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: microsoft/dotnet:2.0.3-sdk-jessie
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo
    environment:
      PACKAGE_VERSION: 1.0.0.${CIRCLE_BUILD_NUM}
    branches:
      only: master

    steps:
      - checkout
      
      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - node_modules-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - node_modules-

      - run: dotnet restore SharpExtensions.sln
      - run: dotnet test src/SharpExtensions.Test/SharpExtensions.Test.csproj
      - run: dotnet pack src/SharpExtensions/SharpExtensions.csproj -o ../../ --include-symbols /p:Version=1.0.0.${CIRCLE_BUILD_NUM}
      - run: dotnet pack src/SharpExtensions.Json/SharpExtensions.Json.csproj -o ../../ --include-symbols /p:Version=1.0.0.${CIRCLE_BUILD_NUM}
      - run: dotnet nuget push SharpExtensions.1.0.0.${CIRCLE_BUILD_NUM}.symbols.nupkg -k ${NUGET_API_KEY} -s nuget.org
      - run: dotnet nuget push SharpExtensions.Json.1.0.0.${CIRCLE_BUILD_NUM}.symbols.nupkg -k ${NUGET_API_KEY} -s nuget.org

      # - persist_to_workspace:
      #     root: ~/repo
      #     paths:
      #       - .